In [ ]:
import numpy as np

In [ ]:
A=np.arange(1,13).reshape(3,4)
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
A=np.linspace(32,56,12).reshape(3,4)
print(A)

[[32.         34.18181818 36.36363636 38.54545455]
 [40.72727273 42.90909091 45.09090909 47.27272727]
 [49.45454545 51.63636364 53.81818182 56.        ]]


In [ ]:
B=np.array([45,67,32,56,23,45,98,65]).reshape(1,1,8)
B.resize(2,2,2)#changes the shape of the original array
#reshape -changes  needs saving in another variable
print(B)

[[[45 67 32 56 23 45 98 65]]]


In [ ]:
A=np.array([2,54,36,23])
B=np.array([73,84,90,45])
A-B
print(A-B)
print(A.max())#max and min only accepts numeric data types
print(A.min())
print(A+B)


[-71 -30 -54 -22]
54
2
[ 75 138 126  68]


In [ ]:
A=np.array([2,54,36,23]).reshape(2,2)
B=np.array([73,84,90,45]).reshape(2,2)
print(A)
print("---------------------")
print(B)
print("--------------------")
c=A.dot(B)#also we can use @ symbol for mat multipilication
print(c)
print("-----------------------")
print(A.max(axis=0))#0 indicate coloumns
print("------------------")
print(A.max(axis=1))#1 indicates row wise
print("-----------------------")
print(B.min(axis=0))#0 indicate coloumns
print("------------------")
print(B.min(axis=1))#1 indicates row wise

[[ 2 54]
 [36 23]]
---------------------
[[73 84]
 [90 45]]
--------------------
[[5006 2598]
 [4698 4059]]
-----------------------
[36 54]
------------------
[54 36]
-----------------------
[73 45]
------------------
[73 45]


In [ ]:
#joining arrays!
A=np.array([2,54,36,23]).reshape(2,2)
B=np.array([73,84,90,45]).reshape(2,2)
print(A)
print("---------------------")
print(B)
print("--------------------------")
print("After vertically stacking the array!")
print(np.vstack((A,B)))
print("---------------------")
print("After Horizontally stacking the array!")
print(np.hstack((A,B)))
print(np.stack((A,B),axis=0))
print("------------------")#to print along with group(3d)



[[ 2 54]
 [36 23]]
---------------------
[[73 84]
 [90 45]]
--------------------------
After vertically stacking the array!
[[ 2 54]
 [36 23]
 [73 84]
 [90 45]]
---------------------
After Horizontally stacking the array!
[[ 2 54 73 84]
 [36 23 90 45]]
[[[ 2 54]
  [36 23]]

 [[73 84]
  [90 45]]]
------------------
[[[ 2 36]
  [54 23]]]


In [ ]:
A=np.arange(30).reshape(2,3,5)
print(A)
print("after stack")

print(np.dstack(A))#no.of rows-->no.of grps
#no.of col in every grp-->no.of rows in every grps


[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
after stack
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


In [ ]:
A=np.arange(50).reshape(5,10)
print(A)
print("after splitting")
print(np.vsplit(A,5))#it splits vertically as 5 parts
print("---------------")
print(np.vsplit(A,(1,3)))#it splits vertically upto 1 one array and (2,3)as one array that means it splits upto 3 and remaing will under go as another array...
print("-----------")
print(np.hsplit(A,5))
print("---------------")
print(np.hsplit(A,(1,3)))


[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
after splitting
[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]), array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]]), array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39]]), array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])]
---------------
[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]]), array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])]
-----------
[array([[ 0,  1],
       [10, 11],
       [20, 21],
       [30, 31],
       [40, 41]]), array([[ 2,  3],
       [12, 13],
       [22, 23],
       [32, 33],
       [42, 43]]), array([[ 4,  5],
       [14, 15],
       [24, 25],
       [34, 35],
       [44, 45]]), array([[ 6,  7],
       [16, 17],
      

In [ ]:
A=np.array([21,40,32,4,3,12,89,78,60,74,76,93]).reshape(3,4)
print(A)
print(A.argmax(axis = 0))  #positions[0,1,2,3]
print(A.argmax(axis = 1))             0,1,2,3]
print(A.argmin(axis = 0))
print(A.argmin(axis = 1))

[[21 40 32  4]
 [ 3 12 89 78]
 [60 74 76 93]]
[2 2 1 2]
[1 2 3]
[1 1 0 0]
[3 0 0]


In [ ]:
#mean,median,std,var
A=np.array([12,34,25,66,71,88])
print("Mean:",np.mean(A))
print("Median:",np.median(A))

print("Variance:",np.var(A))
print("Standard deviation:",np.std(A))




Mean: 49.333333333333336
Median: 50.0
Variance: 743.888888888889
Standard deviation: 27.274326552435515


In [ ]:
A=np.pi#pi=180
print(A)#radians

3.141592653589793


In [ ]:
 B=np.array([np.pi/4,np.pi/3,np.pi/2,np.pi])
print(B)

[0.78539816 1.04719755 1.57079633 3.14159265]


In [ ]:
np.rad2deg(A)

180.0

In [ ]:
print(np.rad2deg(B))

[ 45.  60.  90. 180.]


In [ ]:
C=np.array([30,45,60,23,87,56])
D=np.deg2rad(C)
print(D)

[0.52359878 0.78539816 1.04719755 0.40142573 1.51843645 0.97738438]


In [ ]:
np.sin(C)

array([-0.98803162,  0.85090352, -0.30481062, -0.8462204 , -0.82181784,
       -0.521551  ])

In [ ]:
np.cos(C)

array([ 0.15425145,  0.52532199, -0.95241298, -0.53283302,  0.56975033,
        0.85322011])

In [ ]:
np.tan(C)

array([-6.4053312 ,  1.61977519,  0.32004039,  1.58815308, -1.44241747,
       -0.61127369])

In [ ]:
np.arcsin(1)  #sin^-1

1.5707963267948966

In [ ]:
np.arctan(1)   #cot^-1

0.7853981633974483

In [ ]:
np.arccos(1)

0.0

In [ ]:
a=6
b=4
print(np.hypot(a,b)) #hypotneuse

7.211102550927978


In [ ]:
A=np.array([90,12,34,56,78,90])
print(np.where(A==90))


(array([0, 5]),)


In [ ]:
A=np.array([90,12,34,57,78,90])
print(np.where(A%2==0))#even


(array([0, 1, 2, 4, 5]),)


In [ ]:
A=np.array([90,12,34,57,78,90])
print(np.where(A>25))#greter than 25


(array([0, 2, 3, 4, 5]),)


In [7]:
import numpy as np
A=np.array([2,3,4,5,6])
print(np.searchsorted(A,5))#outputs the index of a sorted array


3


In [9]:
A=np.array([2,54,36,23])
B=np.array([73,84,90,45])
print(np.add(A,B))
print(np.subtract(A,B))


[ 75 138 126  68]
[-71 -30 -54 -22]


In [10]:
print(np.mod(A,B))

[ 2 54 36 23]


In [11]:
print(np.divide(A,B))

[0.02739726 0.64285714 0.4        0.51111111]


In [12]:
print(np.divmod(A,B))

(array([0, 0, 0, 0]), array([ 2, 54, 36, 23]))


In [14]:
A=np.array([2,54,36,23])
print(np.diff(A))#difference b/w ele and and succesive ele

[ 52 -18 -13]


In [20]:
A=np.array([2,54,90,23])
B=np.array([73,84,90,45])
print(np.union1d(A,B))
print(np.setdiff1d(A,B))
print(np.intersect1d(A,B))

[ 2 23 45 54 73 84 90]
[ 2 23 54]
[90]


[ 3. -3.]


ROUNDING

In [22]:
a1=np.trunc([3.89386,-3.75745])#del decimal part
print(a1)

[ 3. -3.]


In [27]:
a1=np.floor([3.89386,-3.75745])
print(a1)

[ 3. -4.]


In [25]:
a1=np.fix([3.89386,-3.75745])#decimal will become 0000 it give only integer values
print(a1)

[ 3. -3.]


In [26]:
a1=np.round([3.89386,-3.75745])
print(a1)

[ 4. -4.]


In [32]:
a1=np.ceil([3.89386,-3.75745])
print(a1)

[ 4. -3.]


In [30]:
a1=np.round([3,7,9])
print(np.cumsum(a1))

[ 3 10 19]


In [31]:
a1=np.round([3,7,9])
print(np.cumprod(a1))

[  3  21 189]


In [34]:
print(np.lcm(12,46))
print(np.gcd(345,35))

276
5


In [35]:
a=np.array([4,8,12])
print(np.gcd.reduce(a))

4


In [36]:
a=np.array([4,8,12])
print(np.lcm.reduce(a))

24


In [37]:
a=np.array([[1,2],[3,4]])
print(np.linalg.inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [38]:
from numpy import random as rd

In [40]:
a=rd.rand()# n #default values from 0 to 0.99
print(a)

0.22135754571663402


In [47]:
a=rd.rand(10)#10 no's prints
print(a)
b=rd.randint(4)
print(b)

[0.65389326 0.83993226 0.58156972 0.28291572 0.94212154 0.12728309
 0.18198251 0.74472957 0.83960059 0.50697512]
3


In [50]:
a=rd.randint(50,size=(2,3))#limit
b=rd.randint(50,size=6)
print(a)
print(b)

[[15 13  4]
 [33 21 40]]
[27 19 47 43 41 46]


In [52]:
A=np.array([1,2,3])
B=np.array([5,9,6])
print(np.inner(A,B))#(1*5)+(2*9)+(3*6)
print(np.outer(A,B))#1*5,1*9,1*6
                  #->2*5,2*9,2*6

41
[[ 5  9  6]
 [10 18 12]
 [15 27 18]]


In [53]:
A=np.array([1,2,3])
B=np.array([5,9,6])
print(np.cross(A,B))#(2*6)-(9*3)(ex;det)

[-15   9  -1]
