In [ ]:
#variable
a = 10
print("i am ",a, "years old")

i am  10 years old


In [ ]:
#adding two integer variables
a=int (input("enter a value"))
b=int (input("enter b value"))

c=a+b
print("sum is" ,c)
print("diff is" ,a-b)
print("product is" ,a*b)
print("quotient is" ,a/b)
print("remainder is" ,a%b)
print("Power is" ,a**b)
print("floor div" ,a//55)




enter a value2
enter b value5
sum is 7
diff is -3
product is 10
quotient is 0.4
remainder is 2
Power is 32
floor div 0


In [ ]:
#take the number from the user which is salary.if the salary is more than 50,000 there is a 10%tax print his final salary.
a=int(input("enter the salary:"))
if(a>50000):
  print("the salary reduction is",a-(a*(0.1)))
else:
    print("salary is less than 50000")

enter the salary:200000
the salary reduction is 180000.0


In [ ]:
#get the salary from the user if the salary is more than or equal to 50k apply 10% tax reduction if the salary is less than 50k apply 5% tax.if the salary is more than 70k apply 12%tax.if your salary exceeds 1 lakh print you are promoted to next level.
a=int(input("enter the salary:"))
if(a<=50000):
    print("the salary reduction is",a-(a*(5/100)))
elif(a<=70000):
  print("the salary reduction is",a-(a*(0.1)))

elif(a<=100000):
    print("the salary reduction is",a-(a*(12/100)))
else:
    print("the salary is more than 1lakh you are promoted")

enter the salary:50000
the salary reduction is 47500.0


In [ ]:
a=int(input("enter the value"))
for i in  range(1,11):

  print(a,"*",i,"=",a*i)

enter the value5
5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
5 * 10 = 50


In [ ]:
#while loop

n=int(input("enter value:"))
i=1
while(i<=10):
  print(n,"*",i,"=",n*i)
  i=i+1

enter value:97
97 * 1 = 97
97 * 2 = 194
97 * 3 = 291
97 * 4 = 388
97 * 5 = 485
97 * 6 = 582
97 * 7 = 679
97 * 8 = 776
97 * 9 = 873
97 * 10 = 970


In [ ]:
#create hetrogenious list.
l = ["apple",23,8.9,True]
for i in l:
  print(i)

apple
23
8.9
True


In [ ]:
#mutable list
l1=["apple",23,8.9,67,"people",True]

for i in l:
  print(i)
l1.append("situ")#to add ele in end
l1.insert(4,"hi")
l1.pop(2)#listname.pop(index of ele)
l1.remove(67)#listname.remove(element)
l1.clear()#to clear whole list
print(l1)



apple
23
hi
people
True
situ
[]


In [ ]:
l2=["kav","appu","sam","geethu"]
#list1.extend(list2)
l1.extend(l2)#l1=l1+l2
print(l1)

['apple', 23, 'hi', 'people', True, 'situ', 'kav', 'appu', 'sam', 'geethu']


In [ ]:
#create a list of 10 integetr ele ,print ther squares save these squares in a new list.
l1=[12,143,14,45,34,19,98,56,42,86]
l2=[]
for i in l1:
  l2.append(i*i)
print(l2)


[144, 20449, 196, 2025, 1156, 361, 9604, 3136, 1764, 7396]


In [ ]:
#list comprehension
#newlist=[output for]
l1=[12,143,14,45,34,19,98,56,42,86]
l2=[i*i for i in l1 if i>50]
print(l2)

[20449, 9604, 3136, 7396]


In [1]:
#list comprehension
#newlist=[(st of if) if (cond) else (st of else) for]
l1=[12,143,14,45,34,19,98,56,42,86]
l2=[i*i  if i>50 else "X" for i in l1]
print(l2)

['X', 20449, 'X', 'X', 'X', 'X', 9604, 3136, 'X', 7396]


In [11]:
#take the salary from the user if salary is < 50k 10% TAX.other wise 15% tax.
i=int(input("ENTER VALUE:"))
l1=[i-(i*(10/100)) if i<50000 else i-(i*(15/100)) ]
print(l1)

ENTER VALUE:78000
[66300.0]


In [12]:
#sal list if salary is < 50k 10% TAX.other wise 15% tax
sal_list=[459000,89000,56000,67544]
l1=[i-(i*(10/100)) if i<50000 else i-(i*(15/100)) for i in sal_list]
print(l1)


[390150.0, 75650.0, 47600.0, 57412.4]


In [23]:
#create dict
dict1={"mentor":'jwalitha',"mentor":'likitha',34:'appu',67:'sam',78:'kav'}
print(dict1)
print(dict1.keys())
print(dict1.values())
print(dict1[34])

{'mentor': 'likitha', 34: 'appu', 67: 'sam', 78: 'kav'}
dict_keys(['mentor', 34, 67, 78])
dict_values(['likitha', 'appu', 'sam', 'kav'])
appu


In [27]:
dict3={"Dept":"CSE","details":{"year":"II","sec":"D","Count":71}}
print(dict3["details"]["sec"])
print(dict3["details"])
print("year is",dict3["details"]["year"])
print("section is",dict3["details"]["sec"])
print("Count is",dict3["details"]["Count"])


D
{'year': 'II', 'sec': 'D', 'Count': 71}
year is II
section is D
Count is 71


In [30]:
#zip object in dict
idl=[12,98,43,34,78,100]
names=["suji","joe","appu","situ","lucky","kavya"]
new_zip=(zip(idl,names))

for i in new_zip:
  print(i)


(12, 'suji')
(98, 'joe')
(43, 'appu')
(34, 'situ')
(78, 'lucky')
(100, 'kavya')


In [36]:
#zip and creating dict using built in func
from builtins import dict
idl=[12,98,43,34,78,100]
names=["suji","joe","appu","situ","lucky","kavya"]
new_zip=dict(zip(idl,names))
print(new_zip)

{12: 'suji', 98: 'joe', 43: 'appu', 34: 'situ', 78: 'lucky', 100: 'kavya'}


In [37]:
#Numpy
import numpy as np
A= np.array([1,2,3,4]) #1d array
print(A.ndim)
print(A.shape)

1
(4,)


In [45]:
#Numpy 2d array

A= np.array([[1,2,3,4],[5,6,7,8]])#2d array
#elements in each row =columns
B= np.array([[[1,2,3,4],[5,6,7,8]],[[12,13,14,15],[1,5,6,3]]])
print(A.ndim)
print(A.shape)
print(B.ndim)
print(B.shape)#no.of ele =rows*coloumns*grps
print(A)
print(B)

2
(2, 4)
3
(2, 2, 4)
[[1 2 3 4]
 [5 6 7 8]]
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[12 13 14 15]
  [ 1  5  6  3]]]


In [51]:
A=np.ones((3))#1d
B=np.zeros((3,3))#2d
C=np.ones((2,4,3))#3d
print(A)
print(B)
print(C)

[1. 1. 1.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [54]:
#Creating id mat
A=np.eye(4)
print(A)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [56]:
#range of mat
A=np.arange(1,10,2)#start,stop,step
print(A)
print(type(A))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [60]:
#print all the numbers that are div by 8.using arrange b/w the range 1000
A=np.arange(0,1001,8)
print(type(A))
print(A)

<class 'numpy.ndarray'>
[   0    8   16   24   32   40   48   56   64   72   80   88   96  104
  112  120  128  136  144  152  160  168  176  184  192  200  208  216
  224  232  240  248  256  264  272  280  288  296  304  312  320  328
  336  344  352  360  368  376  384  392  400  408  416  424  432  440
  448  456  464  472  480  488  496  504  512  520  528  536  544  552
  560  568  576  584  592  600  608  616  624  632  640  648  656  664
  672  680  688  696  704  712  720  728  736  744  752  760  768  776
  784  792  800  808  816  824  832  840  848  856  864  872  880  888
  896  904  912  920  928  936  944  952  960  968  976  984  992 1000]


In [62]:
#numpy using linspace(spliting elements b/w )
A= np.linspace(2,3,12)#(starting,ending,equal parts)
print(A)

[2.         2.09090909 2.18181818 2.27272727 2.36363636 2.45454545
 2.54545455 2.63636364 2.72727273 2.81818182 2.90909091 3.        ]


In [63]:
#spliting the range of nums into n nums having common differences
A= np.linspace(45,145,14)#(starting,ending,equal parts)
print(A)

[ 45.          52.69230769  60.38461538  68.07692308  75.76923077
  83.46153846  91.15384615  98.84615385 106.53846154 114.23076923
 121.92307692 129.61538462 137.30769231 145.        ]
